#version: "3.9"

name: hsedb

services:
    server:
      build:
        dockerfile: Dockerfile_app
        context: .
      ports:
        - "8080:8080"
      depends_on:
        db:
          condition: service_healthy
        cache:
          condition: service_healthy

    db-migrator:
      build:
        dockerfile: goose/Dockerfile
      command: ["postgresql://gotype:gotypepwd@db:5432/gotypedb", "up"]
      depends_on:
        db:
          condition: service_healthy

    db:
      restart: always
      image: postgres:16
      environment:
        POSTGRES_DB: "gotypedb"
        POSTGRES_USER: "gotype"
        POSTGRES_PASSWORD: "gotypepwd"
        PGDATA: "/var/lib/postgresql/data/pgdata"
        POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      ports:
        - '5432:5432'
      volumes:
        - ./postgres-data:/var/lib/postgresql/data
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U gotype -d gotypedb" ]
        interval: 10s
        timeout: 5s
        retries: 5
        start_period: 10s

    cache:
      image: redis:6.2-alpine
      restart: always
      ports:
        - '6379:6379'
      command: redis-server --save 100 10 --loglevel warning --maxmemory 1gb --requirepass gotypepwd
#      volumes:
#        - cache:/data
      healthcheck:
        test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
        interval: 10s
        timeout: 5s
        retries: 5
        start_period: 10s